clc; clear all; close all;
syms m M R Jw n Jm L n anp bet fw g W J_phi vl vr J_psi x1 x2 x3 x4 x5 x6 x7 x8 x9;

f1=((2*m+M)*R*R+2*Jw+2*n*n*Jm)*x3+(M*R*L*cos(x4)-2*n*n*Jm)*x6-M*L*R*x5*x5*sin(x4)-anp*(vl+vr)+2*(bet+fw)*x2-2*bet*x5
f2=(M*L*R*cos(x4)-2*n*n*Jm)*x3+(M*L*L+J_psi+2*n*n*Jm)*x6-M*g*L*sin(x4)-M*L*L*x8*x8*sin(2*x4)+anp*(vl+vr)-2*bet*x2+2*bet*x5
f3=(0.5*m*W*W+J_phi+W*W/2/R^2*(Jw+n*n*Jm)+M*L*L*sin(x4)*sin(x4))*x9+2*M*L*L*x5*x8*sin(x4)*cos(x4)-W/2/R*anp*(vr-vl)+W^2/2/R^2*(bet+fw)*x8

[x3, x6, x9]=solve(f1,f2,f3,x3,x6,x9)
%%
clc; clear all; close all;
syms h1 h2 h3 m M R Jw n Jm L n anp bet fw g W J_phi vl vr J_psi x1 x2 x3 x4 x5 x6 x7 x8 x9 teta_dot teta_2dot psi_dot psi_2dot phi_dot phi_2dot
h1 = (J_psi*anp*vl + J_psi*anp*vr - 2*J_psi*bet*x2 + 2*J_psi*bet*x5 - 2*J_psi*fw*x2 + L^2*M*anp*vl + L^2*M*anp*vr - 2*L^2*M*bet*x2 + 2*L^2*M*bet*x5 - 2*L^2*M*fw*x2 - 4*Jm*fw*n^2*x2 + L^3*M^2*R*x5^2*sin(x4) - 2*L*M*R*bet*x2*cos(x4) + 2*L*M*R*bet*x5*cos(x4) - L^3*M^2*R*x8^2*sin(2*x4)*cos(x4) - L^2*M^2*R*g*cos(x4)*sin(x4) + J_psi*L*M*R*x5^2*sin(x4) + 2*Jm*L*M*g*n^2*sin(x4) + 2*Jm*L^2*M*n^2*x8^2*sin(2*x4) + L*M*R*anp*vl*cos(x4) + L*M*R*anp*vr*cos(x4) + 2*Jm*L*M*R*n^2*x5^2*sin(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4))
 
 
h2 =((2*bet*x2 - anp*(vl + vr) - 2*bet*x5 + x3*(2*Jm*n^2 - L*M*R*cos(x4)) + L*M*g*sin(x4) + L^2*M*x8^2*sin(2*x4))/(M*L^2 + 2*Jm*n^2 + J_psi))
 
 
h3 = -(W^2*bet*x8 + W^2*fw*x8 + R*W*anp*vl - R*W*anp*vr + 4*L^2*M*R^2*x5*x8*cos(x4)*sin(x4))/(2*J_phi*R^2 + Jw*W^2 + Jm*W^2*n^2 + R^2*W^2*m + 2*L^2*M*R^2*sin(x4)^2)

f1 = x2
f2 = h1
f3 = x5
f4 = h2
f5 = x8
f6 = h3

A = [
    diff(f1,x1) ,diff(f1,x2) ,diff(f1,x4) ,diff(f1,x5) ,diff(f1,x7) ,diff(f1,x8) ;
    diff(f2,x1) ,diff(f2,x2) ,diff(f2,x4) ,diff(f2,x5) ,diff(f2,x7) ,diff(f2,x8) ;
    diff(f3,x1) ,diff(f3,x2) ,diff(f3,x4) ,diff(f3,x5) ,diff(f3,x7) ,diff(f3,x8) ;
    diff(f4,x1) ,diff(f4,x2) ,diff(f4,x4) ,diff(f4,x5) ,diff(f4,x7) ,diff(f4,x8) ;
    diff(f5,x1) ,diff(f5,x2) ,diff(f5,x4) ,diff(f5,x5) ,diff(f5,x7) ,diff(f5,x8) ;
    diff(f6,x1) ,diff(f6,x2) ,diff(f6,x4) ,diff(f6,x5) ,diff(f6,x7) ,diff(f6,x8) ;
    ]
B = [
    diff(f1,vl) diff(f1,vr)
    diff(f2,vl) diff(f2,vr)
    diff(f3,vl) diff(f3,vr)
    diff(f4,vl) diff(f4,vr)
    diff(f5,vl) diff(f5,vr)
    diff(f6,vl) diff(f6,vr)
    ]
A = [
    diff(f3,x4) ,diff(f3,x5);
    diff(f4,x4) ,diff(f4,x5);
    ]
B = [
    diff(f3,vl) diff(f3,vr)
    diff(f4,vl) diff(f4,vr)
    ]
%%%%%%%%%%%%%%%%%%%%
%
vl=0;vr=0;x1=0;x2=0;x3=0;x6=0;x9=0;x4=0;x5=0;x7=0;x8=0; m= 0.04; n=30; R=0.0325;M=0.8;L=0.0628; Jw = m*R^2/2; J_psi = M*L^2/3;
Rm = 1.5628; Kt = 0.023385; Jm = 1.175e-05; Kb = 5.9233e-07; anp = n*Kt/Rm; fm=0.0022;
bet = n*Kt*Kb/Rm + fm;
W = 0.168;
fw = 0.0000001;
D = 0.098;
J_phi = M*(W^2+D^2)/12;
g = 9.81;
%%
%%%%%%%%%%%%%%%%%%%%

A =[0,                                                                                                                                                                                                                                                                                                                        1,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                0,                                                                                                                                                                                                                                                                                                                                                          0, 0,                                                                                                                                                                                                                                                                                                                                     0;
    0,      -(2*J_psi*bet + 2*J_psi*fw + 2*L^2*M*bet + 2*L^2*M*fw + 4*Jm*fw*n^2 + 2*L*M*R*bet*cos(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4)),                                                                                                                                                                                                 (L^2*M^2*R*g*sin(x4)^2 - L^2*M^2*R*g*cos(x4)^2 + L^3*M^2*R*x5^2*cos(x4) - L*M*R*anp*vl*sin(x4) - L*M*R*anp*vr*sin(x4) + 2*L*M*R*bet*x2*sin(x4) - 2*L*M*R*bet*x5*sin(x4) + L^3*M^2*R*x8^2*sin(2*x4)*sin(x4) + J_psi*L*M*R*x5^2*cos(x4) + 2*Jm*L*M*g*n^2*cos(x4) + 4*Jm*L^2*M*n^2*x8^2*cos(2*x4) - 2*L^3*M^2*R*x8^2*cos(2*x4)*cos(x4) + 2*Jm*L*M*R*n^2*x5^2*cos(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4)) - ((2*cos(x4)*sin(x4)*L^2*M^2*R^2 - 4*Jm*sin(x4)*L*M*R*n^2)*(J_psi*anp*vl + J_psi*anp*vr - 2*J_psi*bet*x2 + 2*J_psi*bet*x5 - 2*J_psi*fw*x2 + L^2*M*anp*vl + L^2*M*anp*vr - 2*L^2*M*bet*x2 + 2*L^2*M*bet*x5 - 2*L^2*M*fw*x2 - 4*Jm*fw*n^2*x2 + L^3*M^2*R*x5^2*sin(x4) - 2*L*M*R*bet*x2*cos(x4) + 2*L*M*R*bet*x5*cos(x4) - L^3*M^2*R*x8^2*sin(2*x4)*cos(x4) - L^2*M^2*R*g*cos(x4)*sin(x4) + J_psi*L*M*R*x5^2*sin(x4) + 2*Jm*L*M*g*n^2*sin(x4) + 2*Jm*L^2*M*n^2*x8^2*sin(2*x4) + L*M*R*anp*vl*cos(x4) + L*M*R*anp*vr*cos(x4) + 2*Jm*L*M*R*n^2*x5^2*sin(x4)))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4))^2, (2*J_psi*bet + 2*L^2*M*bet + 2*L^3*M^2*R*x5*sin(x4) + 2*L*M*R*bet*cos(x4) + 2*J_psi*L*M*R*x5*sin(x4) + 4*Jm*L*M*R*n^2*x5*sin(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4)), 0,                                                (- 2*R*x8*sin(2*x4)*cos(x4)*L^3*M^2 + 4*Jm*x8*sin(2*x4)*L^2*M*n^2)/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4));
    0,                                                                                                                                                                                                                                                                                                                        0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                0,                                                                                                                                                                                                                                                                                                                                                          1, 0,                                                                                                                                                                                                                                                                                                                                          0;
    0, (4*Jw*bet + 2*M*R^2*bet - 4*Jm*fw*n^2 + 4*R^2*bet*m + 2*L*M*R*bet*cos(x4) + 2*L*M*R*fw*cos(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4)), (L*M^2*R^2*g*cos(x4) + 2*L^2*M^2*R^2*x8^2*cos(2*x4) - L^2*M^2*R^2*x5^2*cos(x4)^2 + 2*Jw*L*M*g*cos(x4) + L^2*M^2*R^2*x5^2*sin(x4)^2 + 4*Jw*L^2*M*x8^2*cos(2*x4) + L*M*R*anp*vl*sin(x4) + L*M*R*anp*vr*sin(x4) - 2*L*M*R*bet*x2*sin(x4) + 2*L*M*R*bet*x5*sin(x4) - 2*L*M*R*fw*x2*sin(x4) + 2*Jm*L*M*g*n^2*cos(x4) + 2*L*M*R^2*g*m*cos(x4) + 4*Jm*L^2*M*n^2*x8^2*cos(2*x4) + 4*L^2*M*R^2*m*x8^2*cos(2*x4) + 2*Jm*L*M*R*n^2*x5^2*cos(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4)) + ((2*cos(x4)*sin(x4)*L^2*M^2*R^2 - 4*Jm*sin(x4)*L*M*R*n^2)*(2*Jw*anp*vl + 2*Jw*anp*vr - 4*Jw*bet*x2 + 4*Jw*bet*x5 + M*R^2*anp*vl + M*R^2*anp*vr - 2*M*R^2*bet*x2 + 2*M*R^2*bet*x5 + 2*R^2*anp*m*vl + 2*R^2*anp*m*vr + 4*Jm*fw*n^2*x2 - 4*R^2*bet*m*x2 + 4*R^2*bet*m*x5 - L*M^2*R^2*g*sin(x4) - L^2*M^2*R^2*x8^2*sin(2*x4) - 2*Jw*L*M*g*sin(x4) - 2*Jw*L^2*M*x8^2*sin(2*x4) - 2*L*M*R*bet*x2*cos(x4) + 2*L*M*R*bet*x5*cos(x4) - 2*L*M*R*fw*x2*cos(x4) + L^2*M^2*R^2*x5^2*cos(x4)*sin(x4) - 2*Jm*L*M*g*n^2*sin(x4) - 2*L*M*R^2*g*m*sin(x4) - 2*Jm*L^2*M*n^2*x8^2*sin(2*x4) - 2*L^2*M*R^2*m*x8^2*sin(2*x4) + L*M*R*anp*vl*cos(x4) + L*M*R*anp*vr*cos(x4) - 2*Jm*L*M*R*n^2*x5^2*sin(x4)))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4))^2,      -(2*x5*cos(x4)*sin(x4)*L^2*M^2*R^2 - 4*Jm*x5*sin(x4)*L*M*R*n^2 + 2*bet*cos(x4)*L*M*R + 2*bet*M*R^2 + 4*bet*m*R^2 + 4*Jw*bet)/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4)), 0, (2*x8*sin(2*x4)*L^2*M^2*R^2 + 4*m*x8*sin(2*x4)*L^2*M*R^2 + 4*Jm*x8*sin(2*x4)*L^2*M*n^2 + 4*Jw*x8*sin(2*x4)*L^2*M)/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4));
    0,                                                                                                                                                                                                                                                                                                                        0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                0,                                                                                                                                                                                                                                                                                                                                                          0, 0,                                                                                                                                                                                                                                                                                                                                          1;
    0,                                                                                                                                                                                                                                                                                                                        0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             (4*L^2*M*R^2*cos(x4)*sin(x4)*(W^2*bet*x8 + W^2*fw*x8 + R*W*anp*vl - R*W*anp*vr + 4*L^2*M*R^2*x5*x8*cos(x4)*sin(x4)))/(2*M*L^2*R^2*sin(x4)^2 + m*R^2*W^2 + 2*J_phi*R^2 + Jm*W^2*n^2 + Jw*W^2)^2 - (4*L^2*M*R^2*x5*x8*cos(x4)^2 - 4*L^2*M*R^2*x5*x8*sin(x4)^2)/(2*J_phi*R^2 + Jw*W^2 + Jm*W^2*n^2 + R^2*W^2*m + 2*L^2*M*R^2*sin(x4)^2),                                                                                                                                                                                                                                                  -(4*L^2*M*R^2*x8*cos(x4)*sin(x4))/(2*J_phi*R^2 + Jw*W^2 + Jm*W^2*n^2 + R^2*W^2*m + 2*L^2*M*R^2*sin(x4)^2), 0,                                                                                                                                                                                                               -(W^2*bet + W^2*fw + 4*L^2*M*R^2*x5*cos(x4)*sin(x4))/(2*J_phi*R^2 + Jw*W^2 + Jm*W^2*n^2 + R^2*W^2*m + 2*L^2*M*R^2*sin(x4)^2)]
 
B =[                                                                                                                                                                                                                                                                                  0,                                                                                                                                                                                                                                                                                  0;
               (M*anp*L^2 + M*R*anp*cos(x4)*L + J_psi*anp)/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4)),               (M*anp*L^2 + M*R*anp*cos(x4)*L + J_psi*anp)/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4));
                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                  0;
-(2*Jw*anp + M*R^2*anp + 2*R^2*anp*m + L*M*R*anp*cos(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4)), -(2*Jw*anp + M*R^2*anp + 2*R^2*anp*m + L*M*R*anp*cos(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4));
                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                  0;
                                                                                                                                                                                                 -(R*W*anp)/(2*J_phi*R^2 + Jw*W^2 + Jm*W^2*n^2 + R^2*W^2*m + 2*L^2*M*R^2*sin(x4)^2),                                                                                                                                                                                                  (R*W*anp)/(2*J_phi*R^2 + Jw*W^2 + Jm*W^2*n^2 + R^2*W^2*m + 2*L^2*M*R^2*sin(x4)^2)]
                                                                                                                                                                                             

%%

% Q_W=[6000    0        0       0       0        0;
%      0      1        0       0       0        0;
%      0      0       9000    0       0        0;
%      0      0        0       0.00000001       0        0;
%      0      0        0       0       7000        0;
%      0      0        0       0       0        1];
%  
 
Q_W=[4000    0        0       0       0        0;
     0      600        0       0       0        0;
     0      0       9000    0       0        0;
     0      0        0       0.0001       0        0;
     0      0        0       0       2500        0;
     0      0        0       0       0       25];


R_W = [20 0;0 20];
K = lqr(A,B,Q_W,R_W)
%%
C = [1 0 0 0 0 0;
     0 0 1 0 0 0;
     0 0 0 0 1 0];
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% G = diag([1,1,1,1,1,1]);  
% QN=diag([1,1,1,1,1,1])*0.00005;
% RN=diag([1,100,1]);
% L=lqe(A,G,C,QN,RN)